### ISSUE TITLE
Question: Folder structure

### ISSUE THREAD

**Issue by Zingam** [ShiftMediaProject/libvpx#1]
Thank you for the pre-compiled redistributes!

Do the .zip files found here:
https://shiftmediaproject.github.io/
have the default folder structure that is created by the install/build command of the source libraries?
I wonder if the CMake's modules for the find_package command will work by default or they'll need to be changed to support your distributions?

**Comment by Sibras** [comment]
The folder structure is based on the default linux style of bin/lib etc. However within each of these folders there is a separate arch folder (x86/x64) which there isnt a standard way of doing (often your only allowed to have 1 of those). So the folder structure used is designed to remain consistent over all the binaries provided on the web site for all the different projects. Many of these projects have different ways of arranging installed folder layouts on Windows that dont always align with the standard used here. This means that there isnt really a standard way that find_packages looks for things (it does different things for different projects). Which makes it difficult to support it consistently for all projects.

That said I havnt tested it with libvpx so i dont know whether it picks it up or not. Worst comes to the worst you can simply just move the files provided here into a different structure that it does pick up.
