### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by WindowsNT** [ShiftMediaProject/libvpx#5]
This looks promising, but the binaries provided include only some vpx files, but not all of them. For example, video_writer.h is used by the examples.

Any example using the compiled library?

**Comment by Sibras** [comment]
The examples in the repo use other source files apart from just those in the examples folder. These files are not part of the binary release as they are not part of the library interface. So video_writer.h is included from the repos root. The libvpx writers did it this way so they can reuse source code between the examples and other parts of libvpx. It can make it a bit confusing if your just looking at the source file for each example as its not immediately obvious that it requires linking in additional local source files to work.

So you can see what files are required for each example program by reading the contents of 'examples.mk'.

Another option would be to look at the ffmpeg source code for its libvpx wrapper. Or there's the google option (but i havnt actually tried that myself)
