### ISSUE TITLE
Release assets for Visual Studio 2022

### ISSUE THREAD

**Issue by jamesobutler** [ShiftMediaProject/libvpx#7]
I see the latest commits for this repo have been for Visual Studio 2022 (msvc 17), but there hasn't been release assets uploaded for it yet. @Sibras Are there plans to upload a download asset for Visual Studio 2022?

https://github.com/ShiftMediaProject/libvpx/releases/tag/v1.8.1-1 was the first release with Visual Studio 2019 (msvc 16) assets.

The Readme current specifies Visual Studio 2013-2017 support.
https://github.com/ShiftMediaProject/libvpx/blob/60906e44b4d568576a23619940855b307d47084b/README.markdown#L17-L20

**Comment by Sibras** [comment]
Currently release assets are generated by the CI when a new tag is made. The next version of libvpx is due around march so when that is released there will be an automatic release asset for that.

As for the readme, that just is out of date and needs updating.

**Comment by Sibras** [comment]
VS2022 releases now available for version 1.12 onwards
